### ISSUE TITLE
Mapping of Solution Configuration to Project Configuration is missing

### ISSUE THREAD

**Issue by plancktimesoftware** [aegoroff/solv#6]
Hi

In cases where the names of the solution's configurations is different from the names of each project's configuration, it is not possible to determine which configuration of a project will be built for a particular solution configuration.
See example:
`{D22D4BB9-7F7C-4DC3-992F-3498D74357C5}.SolutionDebug|x64.ActiveCfg = ProjectDebug|x64`

This line means that when the "SolutionDebug" config is active, then VS will build the project with the "ProjectDebug" config.

This information should be available in the parsed output.

**Comment by aegoroff** [comment]
fixed in v0.16

**Comment by plancktimesoftware** [comment]
Thank you for the extremely quick turnaround time on these 2 issues. Can I donate money to you in any way?

**Comment by aegoroff** [comment]
> plancktimesoftware

thanks but you needn't - it's all not for money :)
